### ISSUE TITLE
[stats] Ampliar las últimas iniciativas de cada diccionario de 5 a 20

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi-engine#25]
Restringiendo los campos a:
* id
* título
* fecha
* lugar
* autor

**Comment by joseEnrique** [comment]
@pr3ssh  el autor lo veo mas complicado porque no se sabe que tipo de autor. Que hago?

**Comment by pr3ssh** [comment]
@joseEnrique  Dejamos los campos por ahora tal y como están; esto es, _id, titulo, fecha.
