### ISSUE TITLE
Explicación de por qué puede haber inicitivas sin fecha (ni de registro ni de actualizacion)

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi-engine#44]
Aunque pueda cambiar la de actualizacion si se produce algun cambio.

**Comment by pr3ssh** [comment]
@CIECODE esto es importante que lo conozcas.

**Comment by CIECODE** [comment]
Hola @pr3ssh @joseEnrique 
No he entendido bien si es una pregunta para mi o si es algo que estáis averiguando vosotros.
A priori, no se me ocurre ningún acto que no tenga fecha, en la medida en la que todos son publicados en algún boletín oficial de las Cortes... ¿Alguna pista más?
Javi

**Comment by joseEnrique** [comment]
@CIECODE hay algunas iniciativas que pueden no tener la fecha. Siempre que salga "Desconocida" es porque el scraper no es capaz de coger la fecha de como suele cogerla

**Comment by CIECODE** [comment]
Hola @joseEnrique 
Ok. Se me ocurren dos preguntas al respecto:
1. ¿Sabes si es por un tipo de actos concretos o por cualquier otra razón "casual", por ejemplo, que lo hayan publicado puntualmente de forma distinta?
2. ¿Qué implicaciones puede tener eso para nuestro "sistema de publicación" de información? ¿Habría que decidir nosotros qué fecha le damos? Se me ocurre que le demos como "fecha de registro" la fecha en la que TIPI tiene por vez primera conocimiento de su existencia; y como fecha de actualización, el mismo criterio que con el resto: cada vez que haya alguna modificación sobre su estado de tramitación.
¿Os parece?
Abrazo.
Javi

**Comment by joseEnrique** [comment]
Hola @CIECODE ,
Respecto a la primera, es de forma casual y se dan en algunas.
Respecto a la segunda, te he respondido en la #43

**Comment by pr3ssh** [comment]
La solución que se le da al segundo apartado no es comoleta ya que dependerá de cuándo lancemos Tipi oara que tome una fecha de registro u otras. No sé si es mejor dejarlas vacias (por no dar información engañosa). Otra cosa es que nosotros bubiésemos cargado todo al inicio de legislatura y ya estuviéramos en marcha.

**Comment by CIECODE** [comment]
Hola, 
Respondo aquí a la primera de las cuestiones y a la segunda en #43.
Si es una cosa casual y que no depende de nosotros, no hay más que decir. Ahora vemos en #43 cuál es la mejor forma de proceder. 
Si lo considerais, ¿podemos cerrar este issue ya?
Javi

**Comment by pr3ssh** [comment]
@CIECODE Lo dejamos pues como está o ponemos la fecha vacía? /cc @joseEnrique

**Comment by pr3ssh** [comment]
Lo hablamos en la #43 si.
