### ISSUE TITLE
[scrap] Actualizar el contenido de las iniciativas si las registramos sin texto

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi-engine#46]
En el caso de que una iniciativa se registre en nuestro sistema pero aun no tenga contenido porque no se hayan pulicado sus boletines, procesar los boletines en su escrapeo incremental y desmarcarla (borrando sus ocurrencias de diccionarios) para que se vuelva a procesar.

Nora; Esto solo lo haremos si y si solo si la iniciativa no tiene contenido y encuentra que hay boletines nuevos (con su nuevo contenido).

**Comment by pr3ssh** [comment]
@joseEnrique espero haberlo explicado bien. [Aquí un ejemplo de a lo que nos referimos](http://tipiciudadano.es/tipis/5817b3fecc3072988e1d3185) /cc @CIECODE

**Comment by joseEnrique** [comment]
@pr3ssh @CIECODE que pasa si hay contenido diferente al que teníamos?

**Comment by pr3ssh** [comment]
@joseEnrique Creo que en ese caso perderiamos la actualizacion. Haria una importacion de contenido si y solo si el campo contenido estuviera vacio. Cómo lo ves @CIECODE?

**Comment by CIECODE** [comment]
Hola @pr3ssh y @joseEnrique
Para no dar pasos en falso voy a contestar a cada cosa específica:
- El criterio general de actualización es sólo cuando cambie el estado de tramitación.
- PERO: hemos visto que el Congreso sube al registro de su web actos antes de que los Boletines estén publicados. Ese es el caso que dice Pablo: si no hay Boletines, hace falta volver a procesarla una vez se publique ese Boletín aunque no haya cambio en el Estado de tramitación. Por eso no eentiendo la pregunta de Enrique, dado que estos actos no tendrían contenido por lo que no podría cambiar.
- En un caso más general, en el que sin cambiar el estado de tramitación, cambiara el contenido, creo que habría que volver a procesarla (estoy pensando en el caso en que el Congreso cambie en el registro el Estado de tramitación pero tarde unos días en publicar el Boletín).
¿Cómo lo veis?

**Comment by pr3ssh** [comment]
Los dos primeros los veo (y creo que estan claros no @joseEnrique?) pero el tercero me cuesta a no ser que sepamos detectarlo. Creo que si ya tenemos un contenido y que luego se pueda subir otro boletin que rescatar complica un poco la cosa. No se si el caso base es que se publiquen, al menos,  los boletines al unisono. Hay que verlo antes de dar pasos en falso si. Al menos con el punto 2 cubrimos gran parte de cosas que ahora estamos dejando fuera.
