### ISSUE TITLE
¿Por qué no coinciden las "últimas iniciativas" si entras por el escáner que si entras por "temas"?

### ISSUE THREAD

**Issue by CIECODE** [CIECODE-Madrid/tipi-engine#48]
Hola, 
Me he dado cuenta de que no coinciden las iniciativas que mostramos como "últimas" en un determinado ámbito temático en función de si entras por el escáner que si entras por temas.

Por ej. con cambio climático:
- Por escáner: http://tipiciudadano.es/escaner?dicts=cambio+clim%C3%A1tico+y+pol%C3%ADtica+energ%C3%A9tica&terms=&grupootro=&autor=&fechadesde=&fechahasta=&lugar=&ref=&vtipo=&tramitacion=&titulo=
- Por temas: http://tipiciudadano.es/temas/cambio-climatico-y-politica-energetica

**Comment by pr3ssh** [comment]
@CIECODE Las veo que coinciden...

**Comment by CIECODE** [comment]
Hola @pr3ssh 
Sí, ahora están coincidiendo. Cierro el issue y si se volviera a dar, lo reabrimos.
Javi

**Comment by pr3ssh** [comment]
El ordenamiento siempre es por fecga de actualización. SI vemos que vuelve a ocurrir lo que haríámos es forzar a que siempre ordene por fecha de actualización y titulo.
