### ISSUE TITLE
He detectado a través de que web nos llegan las visitas de Rusia a TIPI!!!

### ISSUE THREAD

**Issue by CIECODE** [CIECODE-Madrid/tipi-engine#49]
Hola @pr3ssh 

Estaba mirando por casualidad el Analytics de TIPI y ha saltado que a tiempo real estaba un usuario conectado desde Rusia. He buscado cuál había sido la URL de acceso y sale esto: motherboard.vice.com.

Me temo que es Spam puro y duro! Y yo que tenía la callada esperanza de que Putin nos fuera a sacar de pobres ;).

Abrazo.

Javi

**Comment by pr3ssh** [comment]
HAHAHA

Pablo Martín Muñoz
Hacker Cívico
