### ISSUE TITLE
En las 214 quitar la recogida de texto y que solo analice el título

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi-engine#50]
Javi Perez:
Es Comparecencia a Petición Propia del Gobierno

**Comment by CIECODE** [comment]
Sí, eso es. 

Genial.

Gracias

**Comment by pr3ssh** [comment]
@CIECODE Se ve que son Comparecencias del Gobierno en Comisión y está configurado apra que solo rescate su título. Puede que fueran anteriores pero ya debe de estar solucionado. Ahora mismo ninguna de las de tipo 214 son tipis (habra que esperar a que vuelva a reetiquetar esta noche o mañana).
